### ISSUE TITLE
Vertical metrics

### ISSUE THREAD

**Issue by Fonthausen** [Fonthausen/Pacifico#1]
@davelab6 @alexeiva @kalapi @ThomasJockin 

The original Pacifico had a UPM of 2048. The highest glyph was 2,604 and the lowest -928. When added together I came to a total of 3,532, which is 172% of the UPM.

In the new file I am working on I scaled everything down. Based on the same glyphs and an UPM of 1,000, the highest glyph is now 890, the lowest -317. This adds up to 121 % of the UPM.

This number will be lower, because I intend making .case accents which will be much flatter. Thus enabling us to add Vietnamese much easier.

We have decided to make Pacifico a raisin with the intention of making it a very good typeface. But if we change the vertical metrics, it will have effect. Remember, we want to add a weight to it. Shall I carry on with the new vertical metrics ?

**Comment by kalapi** [comment]
@Fonthausen My best advise would be to wait until I can determine how best to deal with the vertical metrics issue. I'll post an update soon!

**Comment by Fonthausen** [comment]
Sounds good. 

When it comes to Pacifico, keep in mind a lot has to be done and it is really too big :)

**Comment by davelab6** [comment]
@Fonthausen I think you should carry on in whatever way you think is best, and we'll figure out what to do as we go :) @crystaltype is having similar concerns. 

I sounds like by scaling everything down as well as changing the UPM, that the visual size of the typeface will be different. I think this is not ideal, because it will be very disruptive for all existing users when we push this update. I think a small amount of visual change is fine - eg, keeping the total size around 170% of UPM, with new v metrics and new spacing/kerning

**Comment by Fonthausen** [comment]
For the moment I have enough to do. I am working with brushes in Illy to redraw the basic shapes with the right contrast. 

This will keep me busy for a while and give you some time to figure out what is possible with the vertical metrics. I would prefer to have this solved before I start the final drawings in Glyphs. Because I am not a friend of rescaling good outlines.

![schermafbeelding 2016-07-11 om 14 54 33](https://cloud.githubusercontent.com/assets/20181530/16731265/68422016-4777-11e6-9bbd-497e4d78c053.png)

**Comment by davelab6** [comment]
@m4rc1e solved this in the end :) Please close
